import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/main/header";
import Menu from "@/components/main/menu";


const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({ subsets: ["latin"] });

// (function (d) {
//     var config = {
//             kitId: "fcz7fus",
//             scriptTimeout: 3000,
//             async: true,
//         },
//         h = d.documentElement,
//         t = setTimeout(function () {
//             h.className =
//                 h.className.replace(/\bwf-loading\b/g, "") + " wf-inactive";
//         }, config.scriptTimeout),
//         tk = d.createElement("script"),
//         f = false,
//         s = d.getElementsByTagName("script")[0],
//         a;
//     h.className += " wf-loading";
//     tk.src = "https://use.typekit.net/" + config.kitId + ".js";
//     tk.async = true;
//     tk.onload = tk.onreadystatechange = function () {
//         a = this.readyState;
//         if (f || (a && a != "complete" && a != "loaded")) return;
//         f = true;
//         clearTimeout(t);
//         try {
//             Typekit.load(config);
//         } catch (e) {}
//     };
//     s.parentNode.insertBefore(tk, s);
// })(document);

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pt-br">

            <body className={inter.className}>
                <Header />
                <main>
                {children}
                </main>
                <Menu />
            </body>
            {/* <Script strategy="beforeInteractive" src="/font.js" /> */}
        </html>
    );
}
